/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MappingsRouteImport } from './routes/mappings'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ArchiveImportIdRouteImport } from './routes/archive.$importId'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicLocalModelRelayRouteImport } from './routes/api/public/local-model-relay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsRoute = MappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ArchiveImportIdRoute = ArchiveImportIdRouteImport.update({
  id: '/archive/$importId',
  path: '/archive/$importId',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicLocalModelRelayRoute =
  ApiPublicLocalModelRelayRouteImport.update({
    id: '/api/public/local-model-relay',
    path: '/api/public/local-model-relay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mappings': typeof MappingsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/archive/$importId': typeof ArchiveImportIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/local-model-relay': typeof ApiPublicLocalModelRelayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mappings': typeof MappingsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/archive/$importId': typeof ArchiveImportIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/local-model-relay': typeof ApiPublicLocalModelRelayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mappings': typeof MappingsRoute
  '/mcp': typeof McpRoute
  '/models': typeof ModelsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/archive/$importId': typeof ArchiveImportIdRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/local-model-relay': typeof ApiPublicLocalModelRelayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mappings'
    | '/mcp'
    | '/models'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/archive/$importId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/local-model-relay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mappings'
    | '/mcp'
    | '/models'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/archive/$importId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/local-model-relay'
  id:
    | '__root__'
    | '/'
    | '/mappings'
    | '/mcp'
    | '/models'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/archive/$importId'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/local-model-relay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MappingsRoute: typeof MappingsRoute
  McpRoute: typeof McpRoute
  ModelsRoute: typeof ModelsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ArchiveImportIdRoute: typeof ArchiveImportIdRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicLocalModelRelayRoute: typeof ApiPublicLocalModelRelayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$importId': {
      id: '/archive/$importId'
      path: '/archive/$importId'
      fullPath: '/archive/$importId'
      preLoaderRoute: typeof ArchiveImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/local-model-relay': {
      id: '/api/public/local-model-relay'
      path: '/api/public/local-model-relay'
      fullPath: '/api/public/local-model-relay'
      preLoaderRoute: typeof ApiPublicLocalModelRelayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MappingsRoute: MappingsRoute,
  McpRoute: McpRoute,
  ModelsRoute: ModelsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ArchiveImportIdRoute: ArchiveImportIdRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicLocalModelRelayRoute: ApiPublicLocalModelRelayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
