/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MappingsRouteImport } from './routes/mappings'
import { Route as ArchiveImportIdRouteImport } from './routes/archive.$importId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingsRoute = MappingsRouteImport.update({
  id: '/mappings',
  path: '/mappings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveImportIdRoute = ArchiveImportIdRouteImport.update({
  id: '/archive/$importId',
  path: '/archive/$importId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mappings': typeof MappingsRoute
  '/archive/$importId': typeof ArchiveImportIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mappings': typeof MappingsRoute
  '/archive/$importId': typeof ArchiveImportIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mappings': typeof MappingsRoute
  '/archive/$importId': typeof ArchiveImportIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mappings' | '/archive/$importId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mappings' | '/archive/$importId'
  id: '__root__' | '/' | '/mappings' | '/archive/$importId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MappingsRoute: typeof MappingsRoute
  ArchiveImportIdRoute: typeof ArchiveImportIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mappings': {
      id: '/mappings'
      path: '/mappings'
      fullPath: '/mappings'
      preLoaderRoute: typeof MappingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$importId': {
      id: '/archive/$importId'
      path: '/archive/$importId'
      fullPath: '/archive/$importId'
      preLoaderRoute: typeof ArchiveImportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MappingsRoute: MappingsRoute,
  ArchiveImportIdRoute: ArchiveImportIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
